In [9]:
# M is the matrix of the directed graph representing a part of the web where M[i,j]=1 if j links i
# d is the damping factor (usually taken as 0.85)
# x is the maximum number of iterations
# P is the page rank vector
# e is error = 0.001
# D is the difference matrix to check for convergence

  import numpy as np
import math

#reading input - number of nodes and the matrix M
N=int(input("Enter the number of nodes\n"))
m=list( map( float,list(input("Enter the matrix of the directed graph representing the web\n").split(' ')) ) )

# 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0

P=[]
D=[]
#initializing the page rank of each node with 1/N
for i in range(N):
    P.append(round(1/N,3))
    D.append(0)

#converting M to 2-D array    
m=np.array(m)
M=np.reshape(m,(N,N)) 
M=np.transpose(M)

print("Matrix M\n",M)
d=0.85
x=100
e=0.001
c=[]
s=0

#Finding how many nodes a single node links to
for j in range(N):
    s=0
    for i in range(N):
        s=s+M[i,j]
    c.append(s)  

    
#initializing M

for i in range(N):
    for j in range(N):
        if c[j]!=0:
            M[i,j]=float(M[i,j])/float(c[j])
        
       
 #page rank algorithm - with scaling
# P(t+1)=(1-d)/n + dMP(t)

damp=float((1-d)/N);

# iterate max x times
for i  in range(100):
    flag=0
# multiplying M and P(t)    
    temp_matrix=np.matmul(M,P)

    print("Without scaling\n",temp_matrix)

    #temp_matrix= dMP(t)
    for i in range(N):
        temp_matrix[i]=temp_matrix[i]*d



  
    for i in range(N):
        #calculate the difference to check for convergence
        D[i]=round(abs(P[i]-round(temp_matrix[i]+damp,3)),3)
        #P(t+1)= damp + temp_matrix
        P[i]=round(temp_matrix[i]+damp,3)
        #comparing difference with allowed error
        if D[i]>0.001:
            flag=1
    print("With scaling\n",P)
    
    if flag==0:
        print("\n\nThe page rank is converging, that is it is reaching equillibrium\n")
        break
    

Enter the number of nodes
8
Enter the matrix of the directed graph representing the web
0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
Matrix M
 [[0. 0. 0. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]]
Without scaling
 [0.5    0.0625 0.0625 0.0625 0.0625 0.0625 0.0625 0.125 ]
With scaling
 [0.444, 0.072, 0.072, 0.072, 0.072, 0.072, 0.072, 0.125]
[0.319, 0.053, 0.053, 0.053, 0.053, 0.053, 0.053, 0.0]
Without scaling
 [0.341 0.222 0.222 0.036 0.036 0.036 0.036 0.072]
With scaling
 [0.309, 0.207, 0.207, 0.049, 0.049, 0.049, 0.049, 0.08]
[0.135, 0.135, 0.135, 0.023, 0.023, 0.023, 0.023, 0.045]
Without scaling
 [0.227  0.1545 0.1545 0.1035 0.1035 0.1035 0.1035 0.049 ]
With scaling
 [0.212, 0.15, 0.15, 0.107, 0.107, 0.107, 0.107, 0.06]
[0.097, 0.057, 0.05